name: firebase_ml_vision
description: Flutter plugin for Firebase machine learning vision services.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision
version: 0.9.10

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.5
  flutter_driver:
    sdk: flutter
  test: any
  path: ^1.6.2
  path_provider: ^1.6.11
  e2e: ^0.6.1
  flutter_tts: ^2.1.0
  flutter_launcher_icons: ^0.8.1 

flutter_icons:
    image_path: "assets/Icon.png"
    ios: true
    android: true

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebasemlvision
        pluginClass: FirebaseMlVisionPlugin
      ios:
        pluginClass: FLTFirebaseMlVisionPlugin

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
